import type { ContentBlock } from './content';

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: Date;
  attachments?: FileAttachment[];
  /** Inline images generated by AI tools (e.g., generate_image) */
  images?: string[];
  /** Whether an image is currently being generated for this message */
  isGeneratingImage?: boolean;
  /** Currently active tool (web_search, scrape_url, generate_image) */
  activeTool?: string | null;
}

export interface FileAttachment {
  id: string;
  name: string;
  type: string;
  size: number;
}

export interface PageContent {
  text: string;
  images: string[];
  /** Full content blocks with placement info (preferred over flat images array) */
  contentBlocks?: ContentBlock[];
}

export interface Page {
  id: string;
  title: string;
  createdAt: Date;
  updatedAt: Date;
  content?: PageContent;
  chatHistory?: ChatMessage[];
}

export interface PageDraft extends Omit<Page, 'id' | 'createdAt' | 'updatedAt'> {
  id?: string;
}
